#!/usr/bin/env bash
# Base script
# Basic and manditory settings for the base of a CustomPiOS build
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -ex

if [ -n "$BASE_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "${BASE_APT_MIRROR}" ]; then
  sed -i '1d' /etc/apt/sources.list
fi

if [ -n "$BASE_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/"${BASE_USER}"/.pip/pip.conf
  rm -r /home/"${BASE_USER}"/.pydistutils.cfg
fi

#reach device by name
if [ -f /etc/hostname ]; then
    read FILE_HOST_NAME < /etc/hostname
        FILE_HOST_NAME=${FILE_HOST_NAME//$'\n'/}
    else
	    FILE_HOST_NAME=raspberrypi
fi

echo "$BASE_OVERRIDE_HOSTNAME" > /etc/hostname
sed -i -e "s@${FILE_HOST_NAME}@$BASE_OVERRIDE_HOSTNAME@g" /etc/hosts

if [ "${BASE_DISTRO}" == "ubuntu" ];then
    echo "127.0.0.1 ${BASE_OVERRIDE_HOSTNAME}" > /etc/hosts
fi

#cleanup
if [ "${BASE_APT_CLEAN}" = "yes" ]; then
    apt-get clean
fi
apt-get autoremove -y
