#!/usr/bin/env bash
#### G1 Config Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/gingeradditive/G1-Configs

# shellcheck disable=all

# G1CONFIG repo
[[ -n "$G1CONFIG_REPO_SHIP" ]] || G1CONFIG_REPO_SHIP="https://github.com/gingeradditive/G1-Configs"
[[ -n "$G1CONFIG_REPO_BRANCH" ]] || G1CONFIG_REPO_BRANCH="newConfigOrganizzation+"

# Add to $PATH ? (1: yes, 0: no)
[[ -n "$G1CONFIG_ADD_TO_PATH" ]] || G1CONFIG_ADD_TO_PATH="1"
