#!/usr/bin/env bash
#### Ginger config Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/gingeradditive/G1-Configs
# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Ginger Config ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone Ginger Config repo
gitclone GINGERCONFIG_REPO G1-Configs

## Step 3: Move to Ginger Config as working directory
pushd "/home/${BASE_USER}/G1-Configs" &> /dev/null || exit 1

## Step 4: Run Ginger Config install routine
echo_green "Launch Ginger Config install routine ..."
sudo -u "${BASE_USER}" bash ./install.sh

## Step 5: Leave Ginger Config
popd &> /dev/null || exit 1

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing Ginger Config ... DONE!"