#!/usr/bin/env bash
# Installs RatOS
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# Add root rights to X11
echo_green "Adding root rights to X11.."
echo needs_root_rights=yes>>/etc/X11/Xwrapper.config

echo_green "Installing KlipperScreen"

cd /home/pi
gitclone KLIPPERSCREEN KlipperScreen
cd /home/pi/KlipperScreen
sudo -u ${BASE_USER} ./scripts/KlipperScreen-install.sh

# Mute output from klipperscreen service
sudo sed -i 's/\[Service\]/\[Service\]\n\StandardOutput=null\nStandardError=null/g' /etc/systemd/system/KlipperScreen.service

sudo systemctl stop KlipperScreen