#!/usr/bin/env bash
#### KAMP Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging
# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing kyleisah KAMP ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git



## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone kyleisah KAMP repo
gitclone KAMP_REPO Klipper-Adaptive-Meshing-Purging

## Step 3: install kyleisah KAMP
ln -s "/home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration printer_data/config/KAMP"
cp "/home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration/KAMP_Settings.cfg" "/home/${BASE_USER}/printer_data/config/KAMP_Settings.cfg"

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing kyleisah KAMP ... DONE!"