#!/bin/bash

set -x
set -e

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

# load common functions
source /common.sh
install_cleanup_trap

source 00-config

# hold linux kernel updates
apt-mark hold "${PKGS[@]}" > /dev/null 2>&1 || true

# execute update
#apt-get -y dist-upgrade

# clean up
apt-get -y autoremove
apt-get clean
