#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

DEPS=(uuid)

apt-get install --yes "${DEPS[@]}"

########################################
# Copy & modify files to /boot         #
########################################

cp /files/headless-nm/headless_nm.txt.template "$BOOT_PATH"/headless_nm.txt.template
cp /files/headless-nm/WiFi-README.txt "$BOOT_PATH"/WiFi-README.txt
sed -i 's|OS_NAME|'"${DIST_NAME}"'|g' "$BOOT_PATH"/WiFi-README.txt

########################################
# Copy & enable service                #
########################################

cp /files/headless-nm/headless_nm.service /etc/systemd/system/headless_nm.service
cp /files/headless-nm/headless_nm /usr/local/bin/headless_nm
sed -i "s#\\\$BOOT_PATH\\\$#${BOOT_PATH}#g" /usr/local/bin/headless_nm
chmod +x /usr/local/bin/headless_nm
systemctl_if_exists enable headless_nm
