#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Enable systemd-networkd Service      #
########################################

systemctl_if_exists enable systemd-networkd.service

########################################
# Disable systemd-networkd-wait-online #
# to start the CANBUS earlier          #
########################################

systemctl_if_exists disable systemd-networkd-wait-online.service

########################################
# Copy config file & udev rules        #
########################################

cp /files/canbus/10-can.rules /etc/udev/rules.d/
cp /files/canbus/25-can.network /etc/systemd/network/
