#!/bin/bash

set -x
set -e

export LC_ALL=C

# load common functions
source /common.sh
install_cleanup_trap

source /files/00-config

SRC_DIR="/home/${BASE_USER}/klipper"
ENV_DIR="/home/${BASE_USER}/klippy-env"

REPO="https://github.com/Klipper3d/klipper.git"
DEPS=(git virtualenv python3-dev \
      python3-matplotlib libffi-dev build-essential libncurses-dev libusb-dev \
      avrdude gcc-avr binutils-avr avr-libc stm32flash dfu-util libnewlib-arm-none-eabi \
      gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0 libusb-1.0-0-dev pkg-config)

echo "Installing Dependencies ..."
apt-get install --yes "${DEPS[@]}"

## Make sure user pi has access to serial ports
usermod -a -G "tty,dialout" "${BASE_USER}"

echo "Cloning repo ..."
pushd "/home/${BASE_USER}" &> /dev/null || exit 1
git clone ${REPO} klipper

create_user_directories

echo "Creating Virtualenv (klippy-env) ..."
sudo -u "${BASE_USER}" virtualenv -p python3 "${ENV_DIR}"
echo "Installing Python Dependencies ..."
sudo -u "${BASE_USER}" "${ENV_DIR}"/bin/pip install -r "${SRC_DIR}"/scripts/klippy-requirements.txt
popd &> /dev/null || exit 1

echo "Copy Service and enable it"
cp /files/klipper.service /etc/systemd/system/klipper.service
cp /files/klipper.env /home/"${BASE_USER}"/printer_data/systemd/klipper.env
chown -R "${BASE_USER}":"${BASE_USER}" /home/"${BASE_USER}"/printer_data/systemd/klipper.env
systemctl_if_exists enable klipper.service
