#!/bin/bash

set -x
set -e

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

# load common functions
source /common.sh
install_cleanup_trap

echo_green "Installing Moonraker and enable Service ..."

BASE_USER=pi
DIR="moonraker"
SRC_DIR="/home/${BASE_USER}/${DIR}"

REPO="https://github.com/Arksine/moonraker.git"
DEPS="git jq"

DIRS="printer_data printer_data/config printer_data/comms printer_data/logs \
      printer_data/systemd"

apt-get install --yes ${DEPS}

echo_green "Cloning Repository"
pushd "/home/${BASE_USER}" &> /dev/null || exit 1
git clone ${REPO} ${DIR}

echo_green "Creating Directories "
for tmp in ${DIRS}; do
    if [[ ! -d "/home/${BASE_USER}/${tmp}" ]]; then
        echo "Creating ${tmp}"
        mkdir -p "/home/${BASE_USER}/${tmp}"
        chown -R "${BASE_USER}:${BASE_USER}" "/home/${BASE_USER}/${tmp}"
    fi
done

echo_green "Installing Dependencies"

# Use the SCRIPTS_PATH from the Bash environment to locate the system-dependencies.json file
SCRIPTS_PATH="/home/${BASE_USER}/${DIR}/scripts"
DEBIAN_DEPS=$(jq -r '.debian | join(" ")' "$SCRIPTS_PATH/system-dependencies.json")

# Now you can use the SYSDEPS variable in your Bash script
echo "Debian dependencies: $DEBIAN_DEPS"
