#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
readonly REPO="https://github.com/meteyou/sonar-dev.git"
readonly DEPS=(git)

########################################
# Install System Packages              #
########################################

apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone "${REPO}" sonar
popd &> /dev/null || exit 1

########################################
# Packages from Install Script         #
########################################

# Installation script from the cloned repository
INSTALL_SCRIPT="/home/${BASE_USER}/sonar/tools/install.sh"

# Extract the package list from the installation script using grep and sed
PKGLIST=$(grep -m 1 'PKGLIST=' "$INSTALL_SCRIPT" | sed 's/.*PKGLIST="\([^"]*\)".*/\1/')

# Convert string to array
read -ra PKGARRAY <<< "$PKGLIST"
apt-get install --yes "${PKGARRAY[@]}"

########################################
# Run Sonar Installation               #
########################################
pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1
make -- install -s -x -d /home/"${BASE_USER}"/printer_data
popd &> /dev/null || exit 1

########################################
# Enable Service                       #
########################################

systemctl_if_exists enable sonar.service
