#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
readonly REPO="https://github.com/meteyou/sonar-dev.git"
readonly DEPS=(git)

readonly SONAR_UPDATER_CONFIG="./resources/moonraker_update.txt"

########################################
# Install System Packages              #
########################################

apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone "${REPO}" sonar
popd &> /dev/null || exit 1

########################################
# Run Sonar Installation               #
########################################
pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1
make install DATA_PATH=/home/"${BASE_USER}"/printer_data UNATTENDED=1

if [ -f $SONAR_UPDATER_CONFIG ] && [ -f "$MOONRAKER_CONFIG" ] ; then
    cat $SONAR_UPDATER_CONFIG >> "$MOONRAKER_CONFIG"
fi

popd &> /dev/null || exit 1

########################################
# Enable Service                       #
########################################

systemctl_if_exists enable sonar.service
