#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
readonly REPO="https://github.com/meteyou/sonar-dev.git"
readonly BRANCH="refactor/pynar"
readonly DEPS=(git)

########################################
# Install System Packages              #
########################################

apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone "${REPO}" sonar -b "${BRANCH}"
popd &> /dev/null || exit 1

########################################
# Build config and install             #
########################################

pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1

# Create config file
{
  echo "BASE_USER=\"${BASE_USER}\""
  echo "SONAR_DATA_PATH=\"/home/${BASE_USER}/printer_data\""
  echo "SONAR_ADD_SONAR_MOONRAKER=\"1\""
  echo "SONAR_UNATTENDED=\"1\""
} > ./tools/.config

# Run install script
make install

# Remove config file
rm ./tools/.config

popd &> /dev/null || exit 1

########################################
# Enable Service                       #
########################################

systemctl_if_exists enable sonar.service
