#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# General settings
readonly REPO="https://github.com/mainsail-crew/sonar.git"
readonly BRANCH="develop"
readonly DEPS=(git)

########################################
# Install System Packages              #
########################################

apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone "${REPO}" sonar -b "${BRANCH}"
popd &> /dev/null || exit 1

########################################
# Change into Sonar directory          #
########################################

pushd "/home/${BASE_USER}/sonar" &> /dev/null || exit 1

########################################
# Build install config file            #
########################################

touch ./tools/.config
echo "SONAR_CONFIG_PATH=/home/${BASE_USER}/printer_data/config" >> ./tools/.config
echo "SONAR_LOG_PATH=/home/${BASE_USER}/printer_data/logs" >> ./tools/.config
echo "SONAR_MOONRAKER_CONF_PATH=${MOONRAKER_CONFIG}" >> ./tools/.config
echo "SONAR_UNATTENDED=1" >> ./tools/.config

########################################
# Run make install                     #
########################################

make install

########################################
# popd from Sonar directory            #
########################################

popd &> /dev/null || exit 1

########################################
# Enable Service                       #
########################################

systemctl_if_exists enable sonar.service
