#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

# Use DIST_NAME in lowercase as the new hostname
NEW_HOSTNAME=${DIST_NAME,,}

function get_parent {
    grep VERSION_CODENAME /etc/os-release | cut -d '=' -f2
}

########################################
# Create <DIST_NAME>-release file      #
########################################

echo "Create ${DIST_NAME} release file"
echo "${DIST_NAME} release ${RELEASE_TAG} ($(get_parent))" > /etc/"${DIST_NAME,,}"-release

########################################
# Workaround for Armbian based OS      #
########################################

### NOTE: The 'distro' Python package used by Moonraker picks the first file after sorting.
###       This hack is necessary because Armbian relies on upgrades to the original release file.
###       To work around this, we symlink mainsailos-release to aaaa-release, which Moonraker reads.
if [[ -f "/etc/armbian-release" || -f "/etc/orangepi-release" ]]; then
    echo "Applying release file workaround"
    ln -sf /etc/"${DIST_NAME,,}"-release /etc/aaaa-release
fi

########################################
# Set Hostname to DIST_NAME            #
########################################

if [ -f /etc/hostname ]; then
    read -r ORG_HOSTNAME < /etc/hostname
    ORG_HOSTNAME=${ORG_HOSTNAME//$'\n'/}
else
    ORG_HOSTNAME=raspberrypi
fi

echo "$NEW_HOSTNAME" > /etc/hostname
sed -i -e "s@${ORG_HOSTNAME}@$NEW_HOSTNAME@g" /etc/hosts

########################################
# Install dependencies for other       #
# Projects                             #
########################################

echo "Install dependencies for other projects"
DEPS=( \
    # python3-serial is needed later on for possible CAN adapters
    python3-serial \
    # python3-opencv is needed for moonraker-obico by obico in version 2.0
    python3-opencv \
)
apt-get install -y "${DEPS[@]}"
