#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Disable apt-daily &                  #
# apt-daily-upgrade timer              #
########################################

systemctl_if_exists disable apt-daily.timer
systemctl_if_exists disable apt-daily-upgrade.timer
