#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Unhold linux kernel updates          #
########################################

#apt-mark unhold "${PKGS[@]}" > /dev/null 2>&1 || true
