#!/bin/bash

set -x
set -e

export LC_ALL=C

# load common functions
source /common.sh
install_cleanup_trap

source /files/00-config

# unhold linux kernel updates
apt-mark unhold "${PKGS[@]}" > /dev/null 2>&1 || true
