#!/usr/bin/env bash
#### Obico Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/TheSpaghettiDetective/moonraker-obico
# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Moonraker Obico ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone Moonraker Obico repo
gitclone OBICO_REPO moonraker-obico

## Step 3: Move to Moonraker Obico as working directory
pushd "/home/${BASE_USER}/moonraker-obico" &> /dev/null || exit 1

## Step 4: Run Moonraker Obico install routine
echo_green "Launch Moonraker Obico install routine ..."
yes "" | sudo -u "${BASE_USER}" ./install.sh

## Step 5: Leave Moonraker Obico
popd &> /dev/null || exit 1

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing Moonraker Obico ... DONE!"