#!/bin/bash
#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####
# shellcheck disable=all

# Sonar
[ -n "$SONAR_SONAR_REPO_SHIP" ] || SONAR_SONAR_REPO_SHIP=https://github.com/mainsail-crew/sonar.git
[ -n "$SONAR_SONAR_REPO_BRANCH" ] || SONAR_SONAR_REPO_BRANCH=main
[ -n "$SONAR_SONAR_DEPS" ] || SONAR_SONAR_DEPS="git crudini iputils-ping"
[ -n "$SONAR_SONAR_DEFAULT_CONF" ] || SONAR_SONAR_DEFAULT_CONF="mainsail_default.conf"
# Add Sonar to moonraker.conf (update manager) bool (1:yes / 0:no)
[ -n "$SONAR_SONAR_ADD_SONAR_MOONRAKER" ] || SONAR_SONAR_ADD_SONAR_MOONRAKER=1
