#!/bin/sh
# System startup script RatOS

### BEGIN INIT INFO
# Provides:          RatOS
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RatOS dummy service
# Description:       Does nothing at this point.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
logfile="/var/log/vcore.log"

case "$1" in
start)
	echo "$(date +"%Y-%m-%d %T"): Updating RatOS" >> "$logfile"
	if [ -e /tmp/printer ]; then
		echo "RESTART" > /tmp/printer
	fi
	;;
stop)
	echo "$(date +"%Y-%m-%d %T"): Stopping RatOS" >> "$logfile"
	;;
restart)
	echo "$(date +"%Y-%m-%d %T"): Updating RatOS" >> "$logfile"
	;;
*)
	exit 2
	;;
esac
exit 0
