#!/usr/bin/env bash
# Enable Serial Communication by default
# Written by Stephan Wendel <me@stephanwe.de> aka KwadFan
# This file may distributed under GPLv3
# Copyright 2021
########


# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap


echo_green "Setup /boot/config.txt to enable UART Communication..."

cat << EOF >> ${SERIALCOMM_CONFIG_TXT_FILE}

#MainsailOS Specific
#Enables UART Communication by default
enable_uart=1
dtoverlay=disable-bt

[pi0w]
#pi0(w) Specific
enable_uart=1
dtoverlay=pi3-disable-bt

[pi02]
gpu_mem=128
enable_uart=1
dtoverlay=disable-bt

EOF


echo_green "Disable Serial Linux console ..."
sed -i 's/console=serial0,115200 //' "${SERIALCOMM_CMDLINE_TXT_FILE}"


### disable bluetooth and related services
echo_green "Disabling Bluetooth related services..."
systemctl_if_exists disable hciuart.service
systemctl_if_exists disable bluetooth.service
systemctl_if_exists disable bluealsa.service