#!/usr/bin/env bash

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

echo_green "Installing RPI MCU service"

pushd /home/pi/klipper
echo "flashing rpi-mcu"
cp -f /home/pi/printer_data/config/RatOS/boards/rpi/firmware.config /home/pi/klipper/.config
make olddefconfig
make clean
make flash
popd

pushd /home/${BASE_USER}/klipper
sudo cp "./scripts/klipper-mcu-start.sh" /etc/init.d/klipper_mcu
sudo update-rc.d klipper_mcu defaults
popd



# Reset ownership
chown pi:pi -R /home/pi/klipper
