#!/usr/bin/env bash
# Shebang for better file detection
#### rpi_firstb_fix module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# Intentionally left blank
# See start_chroot_script for information
