#!/usr/bin/env bash
#### rpi_firstb_fix module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### Description:
#### This is intended to patch behaviour of raspberry's firstboot script.
#### Related to https://github.com/mainsail-crew/MainsailOS/issues/213

# shellcheck enable=require-variable-braces
## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## Step 1: Patch firstboot issue
echo_green "Patch firstboot issue..."
unpack filesystem/root /
## END Step 1
