#!/usr/bin/env bash
#### Post Rename
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

## Set LC_ALL to prevent errors
export LC_ALL=C

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## unpack postrename
unpack filesystem/root / root
## set executable
sudo chmod 0755 /postrename

## run postrename via rc.local
sed -i 's@exit 0@@' /etc/rc.local
echo -e "/postrename\nexit 0\n" | tee -a /etc/rc.local
