#!/bin/bash

# list from all packages which should be hold during the upgrade process
export HOLD_PKGS=( "linux-image-*" "linux-headers-*" "linux-kbuild-*" "armbian-firmware" "raspi-firmware" "linux-dtb-*" "rpi-eeprom" )

export BASE_USER=pi
