#!/usr/bin/env bash
# https://github.com/Delsian/CanSerial
# Script that installs the CANserial service
# Written by RaymondH
# Thanks to Delsian and bondus
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

echo "CANserial"
echo "$CANSERIAL_VAR"

apt update
apt install wget git cmake -y
cd /home/pi
gitclone CANSERIAL_CANSERIAL_REPO CanSerial
cd CanSerial
sudo -u pi cmake .
sudo -u pi make
cp canserial.service /lib/systemd/system/canserial.service
systemctl enable canserial.service


unpack /filesystem/root /
