#!/usr/bin/env bash
# Moonraker install script
# Script that installs Moonraker API service
# Written by Raymond Himle and Stefan Dej
# Thanks to Arksine
# GPL V3
########


# Source error handling, leave this in place
set -e

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

function skip_apt_update() {
    if [ -f "/var/cache/apt/pkgcache.bin" ] && \
    [ "$(($(date +%s)-$(stat -c %Y /var/cache/apt/pkgcache.bin)))" -lt "3600" ];
    then
        echo_green "APT Database needs no update!"
    else
        # force update
        echo_red "APT Database needs to be updated!"
        apt update
    fi
}

### Only install Dependencies if not installed.
function check_installed_dep() {
    ## Build Array from Var
    local missing_deps
    for i in "$@"; do
        dpkg -l $i > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            missing_deps+=" $i"
        fi 
    done &> /dev/null
    if [ "$(echo ${missing_deps} | wc -w)" -ne 0 ]; then
        echo_red "$(echo $missing_deps | wc -w) missing Packages..."
        echo_green "Installing..."
        apt install --yes "$(echo ${missing_deps} | tr -d '[[:space:]]')"
    else
        echo_green "No Dependencies missing... [SKIPPED]"
    fi
}

unpack /filesystem/home/${BASE_USER} /home/${BASE_USER} ${BASE_USER}
unpack /filesystem/root /


echo_green "Installing Moonraker and enable Moonraker Service"

### install all deps at once for time consumption reasons.
skip_apt_update
check_installed_dep ${MOONRAKER_DEPS}

### clone klipper repo
pushd /home/${BASE_USER}
gitclone MOONRAKER_REPO moonraker


### create python3 virtualenv and install moonraker requirements
pushd /home/${BASE_USER}
echo_green "Creating Virtualenv for Moonraker (moonraker-env) ..."
sudo -u ${BASE_USER} virtualenv -p python3 ${MOONRAKER_PYTHON_DIR}
echo_green "Linking Python3 gpiod packages ..."
sudo -u ${BASE_USER} ln -s /usr/lib/python3/dist-packages/gpiod* ${MOONRAKER_PYTHON_DIR}/lib/python*/site-packages
echo_green "Installing klippy Python Dependencies ..."
sudo -u ${BASE_USER} ${MOONRAKER_PYTHON_DIR}/bin/pip install -r ${MOONRAKER_SRC_DIR}/${MOONRAKER_PYENV_REQ}
popd

### Run sudo-fix.sh
sudo -u ${BASE_USER} "${MOONRAKER_SRC_DIR}/scripts/sudo_fix.sh"

### enable systemd service
systemctl_if_exists enable moonraker.service
