#!/usr/bin/env bash

## Source error handling, leave this in place
set -Eex

## Set LC_ALL to prevent errors
export LC_ALL=C

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_red "DEBUG: -------------------------------------------------"
cd /
ls -al /run/systemd/resolve/stub-resolv.conf || true

echo_red "--------------------------------------------------------"

systemctl status systemd-resolved


echo_red "--------------------------------------------------------"

ping -c 2 google.de || true

echo_red "DEBUG: --------------------------------------------------"

echo_green "Try to fix --------------------------------------------"

cat <<- EOF > /etc/systemd/resolved.conf.d/chroot.conf
[Resolve]
DNS=manual
ResolvConf=/etc/resolv.conf
EOF

systemctl start systemd-resolved

echo_green "Try to fix --------------------------------------------"

echo_red "DEBUG: -------------------------------------------------"
cd /
ls -al /run/systemd/resolve/stub-resolv.conf || true

echo_red "--------------------------------------------------------"

systemctl status systemd-resolved


echo_red "--------------------------------------------------------"

ping -c 2 google.de || true

echo_red "DEBUG: --------------------------------------------------"
