#!/bin/sh
# System startup script vcore3

### BEGIN INIT INFO
# Provides:          vcore3
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: vcore3 dummy service
# Description:       Does nothing at this point.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
logfile="/var/log/vcore.log"

case "$1" in
start)
	echo "$(date +"%Y-%m-%d %T"): Updating vcore3" >> "$logfile"
	echo "RESTART" > /tmp/klipper 
	;;
stop)
	echo "$(date +"%Y-%m-%d %T"): Stopping vcore3" >> "$logfile"
	;;
restart)
	echo "$(date +"%Y-%m-%d %T"): Updating vcore3" >> "$logfile"
	;;
*)
	exit 2
	;;
esac
exit 0
