#!/usr/bin/env bash
# Installs RatOS
# GPL V3
########


# Source error handling, leave this in place
set -xe

sudo -u ${BASE_USER} /home/${BASE_USER}/klipper_config/config/scripts/ratos-post-install.sh

# Stop the configurator
kill $configuratorid
# kill $moonrakerid

