#!/usr/bin/env bash
# Installs RatOS
# GPL V3
########


# Source error handling, leave this in place
set -xe

source /common.sh
install_cleanup_trap

echo_green "Installing RatOS"

pushd /home/pi/klipper_config

gitclone RATOS_CONFIG config
gitclone RATOS_THEME .theme

popd

# Run install script
sudo -u pi bash /home/pi/klipper_config/config/scripts/ratos-install.sh

unpack /filesystem/root /

unpack /filesystem/home/${BASE_USER} /home/${BASE_USER} ${BASE_USER}

sudo update-rc.d ratos defaults