#!/usr/bin/env bash
#### opiconfig - OrangePi Configuration Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### NOTE: This module has to be used after armbian module!!!

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release-info.txt"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}


# Step 1: Copy default config to backup file
cp "${OPICONFIG_CONFIG_TXT_FILE}" "${OPICONFIG_CONFIG_BAK_FILE}"

# Step 2: Enable SPI in armbianEnv.txt depending on device

## OrangePi 3 LTS
if [[ "$(is_board_type)" == "orangepi3-lts" ]]; then
    echo "overlays=spi-spidev1" >> "${OPICONFIG_CONFIG_TXT_FILE}"
fi

## OrangePi 4 LTS
if [[ "$(is_board_type)" == "orangepi4-lts" ]]; then
    echo "overlays=spi-spidev" >> "${OPICONFIG_CONFIG_TXT_FILE}"
    echo "param_spidev_spi_bus=1" >> "${OPICONFIG_CONFIG_TXT_FILE}"
fi

# Step 3: add spi-dev module to /etc/modules
echo "param_spidev_spi_bus=1" >> "${OPICONFIG_MODULES_FILE}"
