#!/usr/bin/env bash
#### KIAUH Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits to th33xitus for his great tool
#### https://github.com/th33xitus/kiauh

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing sonar ..."

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 4: clone KIAUH repo
echo_green "Clone KIAUH repository ..."
gitclone KIAUH_REPO kiauh

## Step 5: Link kiauh.sh in /usr/local/bin as kiauh
if [[ ${KIAUH_ADD_TO_PATH} = "1" ]]; then
    echo_green "Add kiauh to PATH ..."
    sudo ln -s "/home/${BASE_USER}/kiauh/kiauh.sh" "/usr/local/bin/kiauh"
fi

## Finish
echo_green "Installing KIAUH ... DONE!"
