#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

# Image source
#DOWNLOAD_URL_CHECKSUM="http://images.mainsail.xyz/olimexlime2/2023-02-20-armbian-23.02.0-trunk-olimex_lime_2.img.xz.sha256"
#DOWNLOAD_URL_IMAGE="http://images.mainsail.xyz/olimexlime2/2023-02-20-armbian-23.02.0-trunk-olimex_lime_2.img.xz"
DOWNLOAD_URL_CHECKSUM="http://images.mainsail.xyz/olimexlime2/A20-OLinuXino-bullseye-minimal-20220928-143706.img.xz.sha256"
DOWNLOAD_URL_IMAGE="http://images.mainsail.xyz/olimexlime2/A20-OLinuXino-bullseye-minimal-20220928-143706.img.xz"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
