#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ROOT_PARTITION=1

# Image source
DOWNLOAD_URL_CHECKSUM="https://github.com/mainsail-crew/armbian-builds/suites/11067166690/artifacts/562910330"
DOWNLOAD_URL_IMAGE="https://github.com/mainsail-crew/armbian-builds/suites/11067166690/artifacts/562910329"

# export Variables
export BASE_ROOT_PARTITION
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
