#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/orangepi_zero.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/orangepi_zero.img.xz"

# export Variables
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
