#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_tag() {
    local url
    url="https://api.github.com/repos/mainsail-crew/MainsailOS/releases/latest"
    curl "${url}" -s | jq .tag_name -r
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_tag)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG
