#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON snipplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="Mainsail OS"
# shellcheck disable=SC2034
# JSON_DESCRIPTION="!" # <- moved to SBC specific default file
# shellcheck disable=SC2034
JSON_ICON_URL="https://os.mainsail.xyz/rpi-imager.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="systemd"
### NOTE: Move line below according to your images! This is only an example!
# # shellcheck disable=SC2034
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
