#!/usr/bin/env bash
# Shebang for better file detection
#### mainsailos module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### NOTE:
#### python3-serial is needed later on for possible CAN adapters
#### python3-opencv is needed for moonraker-obico by obico in version 2.0

[ -n "$MAINSAILOS_DEPS" ] || MAINSAILOS_DEPS="python3-serial python3-opencv"
