#!/usr/bin/env bash
# MainsailOS Specific Tweaks
# written by Stephan Wendel aka KwadFan
# <me@stephanwe.de>
# GPL V3
########

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Eex

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

# Create mainsailos release file
if [ -f "/etc/mainsailos_version" ]; then
    sudo rm -f /etc/mainsailos_version
fi
function get_parent {
    grep VERSION_CODENAME /etc/os-release | cut -d '=' -f2
}

echo "${DIST_NAME} release ${DIST_VERSION} ($(get_parent))" > /etc/"${DIST_NAME,,}"-release

### Install CANBoot Dependency
apt update
# shellcheck disable=SC2086
check_install_pkgs ${MAINSAILOS_DEPS}
