#!/usr/bin/env bash
#### Shake&Tune Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/Frix-x/klippain-shaketune
# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -EeX

## Set LC_ALL to prevent errors
export LC_ALL=C

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Klippain ShakeTune ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone Klippain ShakeTune repo
gitclone SHAKETUNE_REPO klippain_installer

## Step 3: Move to Klippain ShakeTune as working directory
pushd "/home/${BASE_USER}/klippain_installer" &> /dev/null || exit 1

## Step 5: Run Klippain ShakeTune install routine bypassing user interaction and security checks
# shellcheck disable=SC2016
sed \
  -e 's|if \[ "$EUID" -eq 0 \]; then|if false; then|' \
  -e 's|if ! command -v python3 &> /dev/null; then|if false; then|' \
  -e 's|if \[.*klipper.service.*\]; then|if true; then|' \
  < install.sh > temp_install.sh
chmod +x temp_install.sh

#auto select answer
sudo -u "${BASE_USER}" ./temp_install.sh

## Step 7: remove temp_install.sh
rm temp_install.sh

## Step 8: Leave Klippain ShakeTune
popd &> /dev/null || exit 1

## Step 9: remove Klippain installer folder
rm -rf klippain_installer

## Step 10: leave home dir
popd &> /dev/null || exit 1

echo_green "FIX: virtual env path"
sed -i 's|virtualenv: ~/klippain_shaketune-env|virtualenv: ~/klippy-env|' "/home/${BASE_USER}/printer_data/config/moonraker.conf"

## Finish
echo_green "Installing Klippain ShakeTune ... DONE!"