#!/usr/bin/env bash
#### Shake&Tune Install Module
####
#### Written by Giacomo Guaresi <guaresi.giacomo@gmail.com>
#### Copyright 2022 - till today
####
#### This File is distributed under GPLv3
####

#### All Credits for his great tool
#### https://github.com/Frix-x/klippain-shaketune
# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Eex

## Set LC_ALL to prevent errors
export LC_ALL=C

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing Klippain ShakeTune ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone Klippain ShakeTune repo
gitclone SHAKETUNE_REPO klippain-shaketune

## Step 3: Move to Klippain ShakeTune as working directory
pushd "/home/${BASE_USER}/klippain-shaketune" &> /dev/null || exit 1

#DEBUG 
echo_green "[DEBUG] Listing all service units ..."
sudo -u "${BASE_USER}" systemctl list-units --full -all -t service --no-legend

## Step 4: Run Klippain ShakeTune install routine
echo_green "Launch Klippain ShakeTune install routine ..."
yes "" | sudo -u "${BASE_USER}" ./install.sh -L -U

## Step 5: Leave Klippain ShakeTune
popd &> /dev/null || exit 1

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing Klippain ShakeTune ... DONE!"