#!/bin/bash
#### vendor_overlay module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - till today
#### https://github.com/mainsail-crew/crowsnest
####
#### This File is other than usual licensed under the http://www.wtfpl.net/
#### This means this is only an example on how to deliver your own configurations
#### Feel free to modify to your needs.
#### A short hint that it is based on my work would be nice but isnt crucial :)
####
# shellcheck disable=all

## Source error handling, leave this in place
set -Ee

## Set LC_ALL to prevent errors
export LC_ALL=C

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Trying to unpack vendor config files ..."

## unpack overlay
unpack overlay/printer_data /home/"${BASE_USER}"/printer_data "${BASE_USER}"

echo_green "DEBUG: Print 'printer_data' folder ..."
ls -T /home/"${BASE_USER}"/printer_data/
