#!/usr/bin/env bash
#### mainsail module
####
#### Based on work of:
#### Raymond Himle and meteyou
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Set LC_ALL to prevent errors
export LC_ALL=C

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Installing mainsail Web Frontend and configuration..."

echo_green "Install mainsail dependencies ..."
### install all deps at once for time consumption reasons.
## APT: Update Repo Database and install Dependencies
apt_update_skip
# Disabling shellcheck SC2086, because we want "wordsplitting"
# shellcheck disable=SC2086
check_install_pkgs ${MAINSAIL_DEPS}


### Preparing nginx
echo_green "Configure nginx webserver ..."
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/mainsail /etc/nginx/sites-enabled/


# lower nginx rotate cycle to 2 instead 14
echo_green "Modify logrotate cycle (14d -> 2d) ..."
sudo sed -i 's/rotate 14/rotate 2/' /etc/logrotate.d/nginx

# Fix logrotate.d permsissions
chmod 644 /etc/logrotate.d/*

### Download and Install Mainsail Web Frontend
echo_green "Install mainsail Web Frontend ..."
pushd /home/"${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" wget -q --show-progress -O mainsail.zip "${MAINSAIL_URL}"
sudo -u "${BASE_USER}" unzip mainsail.zip -d /home/"${BASE_USER}"/mainsail
## cleanup
rm /home/"${BASE_USER}"/mainsail.zip


echo_green "Linking log files ..."
# Make sure printer_data/logs exists
if [[ ! -d "/home/${BASE_USER}/printer_data/logs" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "/home/${BASE_USER}/printer_data/logs"
fi
### Link logfiles to klipper_logs
ln -s /var/log/nginx/mainsail-access.log /home/"${BASE_USER}"/printer_data/logs
ln -s /var/log/nginx/mainsail-error.log /home/"${BASE_USER}"/printer_data/logs


### Install mainsail.cfg
## clone repo
echo_green "Installing mainsail.cfg ..."
gitclone MAINSAIL_CONFIG_REPO mainsail-config

# Make sure printer_data/config exists
if [[ ! -d "/home/${BASE_USER}/printer_data/config" ]]; then
    sudo -u "${BASE_USER}" mkdir -p "/home/${BASE_USER}/printer_data/config"
fi
if [[ -f "${MAINSAIL_CONFIG_SRC_PATH}" ]]; then
    sudo -u "${BASE_USER}" \
    ln -sf "${MAINSAIL_CONFIG_SRC_PATH}" "${MAINSAIL_CONFIG_DEST_PATH}"
fi

popd &> /dev/null || exit 1
# Unpack root at the end, so files are modified before
unpack /filesystem/root /
