#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Apply SmartPad specific patches..."
unpack /filesystem/root /
if [[ -f /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf ]]; then
    rm -fv /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf
fi

echo_green "Apply SmartPad specific patches... [DONE]"
# Keep for later use ...
# ## Step 9: Enable spi and/or UART3 on BananaPi M2 Zero
# ### Enable both
# if [[ "$(is_board_type)" == "bananapim2zero" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_UART3}" == "true" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_SPI}" == "true" ]]; then
#     echo_green "Enable UART3 and SPI for 'bananapim2zero' SBC ..."
#     echo "overlays=uart3 spi-spidev" >> "${ARMBIAN_CONFIG_TXT_FILE}"
# fi
# ### UART3 only
# if [[ "$(is_board_type)" == "bananapim2zero" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_UART3}" == "true" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_SPI}" != "true" ]]; then
#     echo_green "Enable UART3 for 'bananapim2zero' SBC ..."
#     echo "overlays=uart3" >> "${ARMBIAN_CONFIG_TXT_FILE}"
# fi
# ### SPI only
# if [[ "$(is_board_type)" == "bananapim2zero" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_UART3}" == "true" ]] \
# && [[ "${ARMBIAN_CONFIG_BPI2ZERO_ENABLE_SPI}" != "true" ]]; then
#     echo_green "Enable SPI for 'bananapim2zero' SBC ..."
#     echo "overlays=uart3" >> "${ARMBIAN_CONFIG_TXT_FILE}"
# fi
# ## END Step 9
