#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}

echo_green "Apply SmartPad specific patches..."
unpack /filesystem/root /
if [[ -f /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf ]]; then
    rm -fv /etc/X11/xorg.conf.d/03-smartpad-rotate-touch.conf
fi

echo_green "Apply SmartPad specific patches... [DONE]"


### Enable Serial and SPI connections by default
if [[ "$(is_board_type)" == "smartpad" ]]; then
    echo_green "Enable Serial and SPI interface on SmartPad..."
    echo "overlays=spi-spidev uart1 uart2" >> "${SMARTPAD_CONFIG_TXT_FILE}"
    echo "param_spidev_spi_bus=1" >> "${SMARTPAD_CONFIG_TXT_FILE}"
    echo_green "Enable Serial and SPI interface on SmartPad... DONE!"
fi

### Install plymouth theme and install yumi Plymouth repository
echo_green "Install Yumi Lab Plymouth theme on SmartPad..."

smartpad_install_theme() {
    local src dest
    dest="/usr/share/plymouth/themes/"
    src="/home/${BASE_USER}/$(basename "${SMARTPAD_PLYMOUTH_REPO/.git/}")"
    src="${src}/pack_2/hexagon_alt"
    if [[ -d "${src}" ]]; then
        sudo cp -vr "${src}" "${dest}"
    fi
    echo_green "Set default theme to ${SMARTPAD_PLYMOUTH_THEME} ..."
    sudo plymouth-set-default-theme "${SMARTPAD_PLYMOUTH_THEME}"
}

pushd "/home/${BASE_USER}" &>/dev/null
git clone "${SMARTPAD_PLYMOUTH_REPO}"
smartpad_install_theme
popd &>/dev/null

echo_green "Install Yumi Lab Plymouth theme on SmartPad... [DONE]"

echo_green "Install yumi-config smartpad_generic ..."
pushd "/home/${BASE_USER}" &>/dev/null
sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/yumi-config.git
echo "DEBUG:"
echo "----------------------------------------------------------"
ls -al /home/"${BASE_USER}"
echo "----------------------------------------------------------"
sudo -u "${BASE_USER}" cp -R /home/"${BASE_USER}"/yumi-config/smartpad-generic/* /home/"${BASE_USER}"/printer_data/config/
rm -rfv "/home/${BASE_USER}/yumi-config"
popd &>/dev/null
echo_green "Install yumi-config smartpad_generic ... [DONE]"

echo_green "Install YUMI_SYNC ..."
pushd "/home/${BASE_USER}" &>/dev/null
sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/YUMI_SYNC.git
cd YUMI_SYNC
chmod +x ./install.sh
./install.sh
cd ..
popd &>/dev/null
echo_green "Install YUMI_SYNC ... [DONE]"

# echo_green "Install moonraker-yumi-lab ..."
# pushd "/home/${BASE_USER}" &>/dev/null
# sudo -u "${BASE_USER}" git clone https://github.com/Yumi-Lab/moonraker-yumi-lab.git
# cd moonraker-yumi-lab
# chmod +x ./install.sh
# ./install.sh
# cd ..
# popd &>/dev/null
# echo_green "Install moonraker-yumi-lab ... [DONE]"

echo_green "Disable KlipperScreen for first boot service..."
systemctl_if_exists disable KlipperScreen.service
