#!/usr/bin/env bash
# Shebang for better file detection
#### YUMIOS module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2024
####
#### This File is distributed under GPLv3
####

#### NOTE:
#### python3-serial is needed later on for possible CAN adapters
#### python3-opencv is needed for moonraker-obico by obico in version 2.0

[ -n "$YUMIOS_DEPS" ] || YUMIOS_DEPS="python3-serial python3-opencv wavemon \
hexedit tcpdump iptraf mc htop dcfldd nano usbutils ranger tldr ncdu \
can-utils multitail fd-find lsof minicom"
