#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration & Install deps         #
########################################

SWAP_CONF_FILE="/etc/dphys-swapfile"
SWAP_SIZE="256"
SWAP_MAX="1024"

DEPS=(i2c-tools)

apt-get install --yes "${DEPS[@]}"

########################################
# Add boot-config.txt to               #
# /boot/config.txt                     #
########################################

cat /files/boot-config.txt >> "$BOOT_PATH"/config.txt

########################################
# Disable serial console to enable     #
# Hardware Serial (PL011).             #
########################################

sed -i 's/console=serial0,115200 //' "$BOOT_PATH"/cmdline.txt

########################################
# Enable i2c modules                   #
########################################

if [[ -f /etc/modprobe.d/raspi-blacklist.conf ]]; then
    sed /etc/modprobe.d/raspi-blacklist.conf -i -e "s/^\(blacklist[[:space:]]*i2c[-_]bcm2708\)/#\1/"
fi

[[ -f /etc/modules ]] || touch /etc/modules
# Uncomment i2c_dev if it exists
sed /etc/modules -i -e "s/^#[[:space:]]*\(i2c[-_]dev\)/\1/"
# Add if doesn't exist
if ! grep -q "^i2c[-_]dev" /etc/modules; then
    printf "i2c-dev\n" >>/etc/modules
fi

########################################
# Disable bluetooth and related        #
# services                             #
########################################

systemctl_if_exists disable hciuart.service
systemctl_if_exists disable bluetooth.service
if ! grep "bookworm" /etc/os-release; then
    systemctl_if_exists disable bluealsa.service
fi

########################################
# Increase swapfile size               #
########################################

if [[ -f "${PICONFIG_SWAP_CONF_FILE}" ]]; then
    echo_green "Increasing swap file size to ${SWAP_SIZE} Mb. Limit to ${SWAP_MAX} Mb"
    sed -i 's/^CONF_SWAPSIZE.*/'CONF_SWAPSIZE="${SWAP_SIZE}"'/' "${SWAP_CONF_FILE}"
    sed -i 's/^#CONF_MAXSWAP.*/'CONF_MAXSWAP="${SWAP_MAX}"'/' "${SWAP_CONF_FILE}"
fi

########################################
# Finalize user setup and set password #
########################################

if [ -f /usr/lib/userconf-pi/userconf ]; then
    hash="$(echo "$BASE_PASSWORD" | openssl passwd -6 -stdin)"
    /usr/lib/userconf-pi/userconf "$BASE_USER" "${hash}"
fi

systemctl_if_exists disable userconfig.service

########################################
# Enable getty                         #
########################################

systemctl_if_exists enable getty@tty1.service

########################################
# Enable sshd                          #
########################################

if [ -f /usr/lib/raspberrypi-sys-mods/imager_custom ]; then
    /usr/lib/raspberrypi-sys-mods/imager_custom enable_ssh
else
    systemctl_if_exists enable ssh
fi

########################################
# Enable passwordless sudo (build)     #
########################################

# Trixie+: raspberrypi-sys-mods no longer ships /etc/sudoers.d/010_pi-nopasswd
# Bookworm and earlier: /etc/sudoers.d/010_pi-nopasswd is already
#
# 98-remove-passwordless-sudo reverts both cases at the end of the build.
RASPI_CONFIG="$(command -v raspi-config || true)"
if [ -n "${RASPI_CONFIG}" ] && grep -q "^do_sudo_pass" "${RASPI_CONFIG}"; then
    SUDO_USER="${BASE_USER}" raspi-config nonint do_sudo_pass 1
elif [ ! -f /etc/sudoers.d/010_pi-nopasswd ]; then
    # Fallback for legacy images that neither have the raspi-config
    # helper nor the pre-shipped nopasswd file.
    echo "${BASE_USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/010_pi-nopasswd
    chmod 440 /etc/sudoers.d/010_pi-nopasswd
fi
