#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

NM_STATE="/var/lib/NetworkManager/NetworkManager.state"

########################################
# Workaround rfkill                    #
########################################

rm /var/lib/systemd/rfkill/*

########################################
# Fix Wireless State                   #
########################################

if [[ -f "$NM_STATE" ]]; then
    sed -i 's/WirelessEnabled=false/WirelessEnabled=true/g' "$NM_STATE"
fi
