#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Remove passwordless sudo access      #
########################################

if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
    sed -e '/^'"${BASE_USER}"'/ s/^#*/#/' -i /etc/sudoers.d/010_pi-nopasswd
fi
