#!/usr/bin/env bash
# Klipper + Moonraker install script
# Script that installs Klipper and the Moonraker API service
# Written by Raymond Himle
# Thanks to KevinOConnor and Arksine
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi

echo "Installing Klipper and Moonraker"
echo "$KLIPPER_MOONRAKER_VAR"

apt update
apt install wget git gpiod -y

#Make sure user pi has access to serial ports
usermod -a -G tty pi
usermod -a -G dialout pi

cd /home/pi
gitclone KLIPPER_MOONRAKER_KLIPPER_REPO klipper
gitclone KLIPPER_MOONRAKER_MOONRAKER_REPO moonraker
sudo -u pi bash /home/pi/./install-custompios.sh
su -c '/home/pi/moonraker/scripts/sudo_fix.sh' - pi

rm /home/pi/install-custompios.sh
# Run installation steps defined above
