#!/usr/bin/env bash
# Klipper + Moonraker install script
# Script that installs Klipper and the Moonraker API service
# Written by Raymond Himle
# Thanks to KevinOConnor and Arksine
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "Installing Klipper and Moonraker"
echo "$MAINSAILOS_VAR"

#sudo -u pi bash /home/pi/./install-custompios.sh
#sudo -u pi bash ./install-custompios.sh
apt update
apt install wget git -y
cd /home/pi
sudo -u pi git clone https://github.com/KevinOConnor/klipper
cd /home/pi/klipper
sudo -u pi git remote add arksine https://github.com/Arksine/klipper.git; git fetch arksine; git checkout arksine/dev-moonraker-testing
cd /home/pi
sudo -u pi git clone https://github.com/Arksine/moonraker.git
sudo -u pi bash /home/pi/./install-custompios.sh
sed -i -e '$i \cp -n /boot/printer.cfg /home/pi/printer.cfg; chown pi:pi /home/pi/printer.cfg &\n' /etc/rc.local
sudo -u pi mkdir /home/pi/sdcard
rm /home/pi/install-custompios.sh
# Run installation steps defined above

# Unpack root at the end, so files are modified before
unpack /filesystem/root /
