#!/usr/bin/env bash
#### MainsailOS Specific Tweaks for orangepi images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## Clean up
## Step 1: Delete root passwd (disables root login)
### Deleting root passwd doesn't let you unlock the account
sudo passwd -d root
## END Step 1

## Step 2: Lock root account (disables root login)
sudo passwd -l root
## END Step 2

## Step 3: Remove passwdless sudo
sed -i '/'"${BASE_USER}"' ALL=(ALL:ALL) NOPASSWD:ALL/d' /etc/sudoers
## END Step 3
