#!/usr/bin/env bash
# Buster Patch
# Should prevent build error due name change of Release Info of raspios buster
# Also brings latest Updates to the Image
# Written by KwadFan
# GPL V3
########

## Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

apt update --allow-releaseinfo-change
apt full-upgrade --yes