#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH="${DIR}"
CUSTOM_PI_OS_PATH=$(<"${DIR}"/custompios_path)
export CUSTOM_PI_OS_PATH
export PATH=$PATH:$CUSTOM_PI_OS_PATH

"${CUSTOM_PI_OS_PATH}"/build_custom_os "$@"
