#!/usr/bin/env bash
# Shebang for better detection of file type

export DIST_NAME=RatOS
export DIST_VERSION=1.2.4
export BASE_IMAGE_ENLARGEROOT=6500
export MODULES="base,pkgupgrade,mainsailos(net,piconfig,klipper,node,is_req_preinstall,moonraker,timelapse,mainsail,crowsnest,sonar,ratos,rpi_mcu,klipperscreen,disable-services(hotspot),password-for-sudo),postrename"
export BASE_IMAGE_RESIZEROOT=600
export BASE_RELEASE_COMPRESS=yes

export BASE_RELEASE_IMG_NAME=`${DIST_NAME}-v${DIST_VERSION}`
export BASE_IGNORE_VARIANT_NAME=yes
export BASE_USER=pi
export BASE_USER_PASSWORD=raspberry

export RPI_IMAGER_NAME="${DIST_NAME}"
export RPI_IMAGER_DESCRIPTION="Modular klipper configuration for supported 3d printers"
export RPI_IMAGER_ICON="https://raw.githubusercontent.com/Rat-OS/RatOS/master/site/static/img/logos/rpi-imager.png"
