#!/usr/bin/env bash
#### MainsailOS Specific procedure for armbian images to replace 'pkgupgrade' module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

#### Description:
#### Due missing packages in our armbian builds and
#### and buggy behaviour of kernel upgrades we have to skip
#### upgrading the kernel package during build time.
#### Kernel upgrade is possible after first boot.

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}


## Install some basic packages that are needed during build
## Package net-tools fixes module 'armbian_net'
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND
apt-get update --allow-releaseinfo-change
apt-get install --yes --assume-yes sudo apt-utils wget net-tools

## Set kernel package on hold
### Orange Pi 3 LTS
if [[ "$(is_board_type)" == "orangepi3-lts" ]]; then
    echo "armbian-firmware hold" | dpkg --set-selections
    echo "linux-image-current-sunxi64 hold" | dpkg --set-selections
    echo "linux-dtb-current-sunxi64 hold" | dpkg --set-selections
fi

### Orange Pi 4 LTS
if [[ "$(is_board_type)" == "orangepi4-lts" ]]; then
    echo "armbian-firmware hold" | dpkg --set-selections
    echo "linux-image-current-rockchip64 hold" | dpkg --set-selections
    echo "linux-dtb-current-rockchip64 hold" | dpkg --set-selections
fi


### Rock Pi 4 SE
if [[ "$(is_board_type)" == "rockpi-4b" ]]; then
    echo "armbian-firmware hold" | dpkg --set-selections
    echo "linux-image-current-rockchip64 hold" | dpkg --set-selections
    echo "linux-dtb-current-rockchip64 hold" | dpkg --set-selections
fi

### Rock CM3
if [[ "$(is_board_type)" == "rock-3a" ]]; then
    echo "armbian-firmware hold" | dpkg --set-selections
    echo "linux-image-edge-rk35xx hold" | dpkg --set-selections
    echo "linux-dtb-edge-rk35xx hold" | dpkg --set-selections
fi

## Run full upgrade
apt-get upgrade --yes --assume-yes

## Revert hold status
### Orange Pi 3 LTS
if [[ "$(is_board_type)" == "orangepi3-lts" ]]; then
    echo "armbian-firmware install" | dpkg --set-selections
    echo "linux-image-current-sunxi64 install" | dpkg --set-selections
    echo "linux-dtb-current-sunxi64 install" | dpkg --set-selections
fi

### Orange Pi 4 LTS
if [[ "$(is_board_type)" == "orangepi4-lts" ]]; then
    echo "armbian-firmware install" | dpkg --set-selections
    echo "linux-image-current-rockchip64 install" | dpkg --set-selections
    echo "linux-dtb-current-rockchip64 install" | dpkg --set-selections
fi

unset DEBIAN_FRONTEND
