#!/usr/bin/env bash
# Installs Rat Rig V-Core 3 config and mainsail theme
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi

echo "V-CoreOS"

cd /home/pi/klipper_config

gitclone RATRIG_OS_CONFIG config

# Run install script
sudo -u pi bash /home/pi/klipper_config/config/scripts/ratos-install.sh

unpack /filesystem/root /

sudo update-rc.d v-coreos defaults