#!/usr/bin/env bash

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

if [[ ! -d /tmp ]]; then
	mkdir /tmp
fi

chmod 777 /tmp

curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
apt update && apt install nodejs yarn -y 
