#!/usr/bin/env bash

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

if [[ ! -d /tmp ]]; then
	mkdir /tmp
fi

chmod 777 /tmp

curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
curl -fsSL https://get.pnpm.io/install.sh | sh -
apt update && apt install nodejs -y 
