#!/usr/bin/env bash

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

if [[ ! -d /tmp ]]; then
	mkdir /tmp
fi

chmod 777 /tmp

curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
apt update && apt install nodejs -y 

npm install -g pnpm
if ! which pnpm &> /dev/null; then
	echo "pnpm not found after sourcing"
	exit 1
fi
