name: "Release"

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:
    inputs:
      release:
        description: 'Als Release veröffentlichen'
        type: boolean
        default: false
      version:
        description: 'Release-Version (Format: X.Y.Z)'
        type: string
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_release_tag.outputs.release_tag }}
      is_release: ${{ steps.check_release.outputs.is_release }}
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4

      - name: "🔎 Check if this is a release build"
        id: check_release
        run: |
          if [[ "${{ github.event.inputs.release }}" == "true" && "${{ github.event.inputs.version }}" != "" ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: "Set release tag"
        id: set_release_tag
        run: |
          if [[ "${{ steps.check_release.outputs.is_release }}" == "true" ]]; then
            echo "release_tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            RELEASE_TAG=$(cat VERSION | tr -d '\n')
            echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: "Create tag if release build"
        if: steps.check_release.outputs.is_release == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}
          echo "${{ github.event.inputs.version }}" > VERSION
          git add VERSION
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4
        with:
          ref: "develop"

      - name: "🛠 Generate matrix from config.yml"
        id: create-matrix
        run: |
          python3 - <<'EOF'
          import os, yaml, json
          with open("config.yml", "r") as f:
              config = yaml.safe_load(f)
          matrix = {"include": config}
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"matrix={json.dumps(matrix)}", file=fh)
          EOF

  build:
    needs: [prepare, generate-matrix]
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4
        with:
          ref: "develop"

      - name: "#️⃣️ Set RELEASE_TAG from VERSION file"
        run: |
          RELEASE_TAG=$(cat VERSION | tr -d '\n')
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: "📁 Create directories"
        run: |
          mkdir -p build
          mkdir -p scripts

      - name: "⬇ Download Image via Torrent"
        if: ${{ endsWith(matrix.img_download_url, '.torrent') }}
        run: aria2c -d build --seed-time=0 --enable-dht=false "${{ matrix.img_download_url }}"

      - name: "⬇ Download Image via wget"
        if: ${{ !endsWith(matrix.img_download_url, '.torrent') }}
        working-directory: ./build
        run: wget ${{ matrix.img_download_url }}

      - name: "🔐 Verify image"
        working-directory: ./build
        run: curl -Ls ${{  matrix.img_hash_url }} | sha256sum -c

      - name: "🛠 Unpack and rename image"
        working-directory: ./build
        run: |
          # search for the image file in the build directory
          IMG_FILE=$(ls *.img.xz | head -n 1)
          echo "Found compressed Image file: ${IMG_FILE}"

          # extract the image file
          xz -d "${IMG_FILE}"

          DECOMPRESSED_FILE="${IMG_FILE%.xz}"
          echo "Image file: ${DECOMPRESSED_FILE}"

          # rename the image file
          mv "${DECOMPRESSED_FILE}" input.img

      - name: "📋 Copy generic and type scripts"
        run: |
          cp -r modules/generic/* scripts/
          cp -r modules/${{ matrix.type }}/* scripts/
          for file in scripts/*.disabled; do
            if [ -e "$file" ]; then
              rm "$file"
            fi
          done

      - name: "📋 Copy special modules"
        run: |
          # Check if special_modules are defined for this configuration
          if [ -n "${{ toJson(matrix.special_modules) }}" ] && [ "${{ toJson(matrix.special_modules) }}" != "[]" ]; then
            # copy additional files for special modules
            if [ -d "modules/special/files" ]; then
              cp -r modules/special/files/* scripts/files/
            fi

            # Convert JSON array to bash array
            MODULES=$(echo '${{ toJson(matrix.special_modules) }}' | jq -r '.[]')

            for module in "${MODULES[@]}"; do
              cp "modules/special/${module}" scripts/
            done
          else
            echo "No special modules defined for ${{ matrix.name }}."
          fi

      - name: "📇 Generate config.local"
        run: |
          echo "Generating config.local file..."
          python3 - <<'EOF'
          import os, json
          env_vars = json.loads(os.environ.get("MATRIX_ENV", "{}"))
          with open("config.local", "w") as f:
              for key, value in env_vars.items():
                  if not key.startswith("EDITBASE_"):
                      key = "EDITBASE_" + key
                  f.write(f"{key}={value}\n")
          EOF
        env:
          MATRIX_ENV: ${{ toJson(matrix.env) }}

      - name: "🔎 Show scripts"
        working-directory: ./scripts
        run: ls -la

      - name: "🏗 Run CustoPiZer"
        uses: OctoPrint/CustoPiZer@1.3
        with:
          workspace: "${{ github.workspace }}/build"
          scripts:  "${{ github.workspace }}/scripts"
          config: "${{ github.workspace }}/config.local"
          environment: '{ "RELEASE_TAG": "${{ env.RELEASE_TAG }}"}'

      - name: "✏ Rename image"
        working-directory: ./build
        run: |
          RELEASE_TAG="${{ env.RELEASE_TAG }}"
          NOW="$(date +"%Y-%m-%d")"

          IMAGE="${NOW}-MainsailOS-${{ matrix.name }}-${RELEASE_TAG}.img"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          mv output.img "${IMAGE}"

      - name: "🛠 Compressing Image"
        working-directory: ./build
        run: |
          CPU_COUNT="$(nproc)"
          echo -e "\e[32mUsing ${CPU_COUNT} Cores for compression...\e[0m"
          xz -efkvz9T"${CPU_COUNT}" ${{ env.IMAGE }} || true

      - name: "🔐 Create hash"
        working-directory: ./build
        run: |
          sha256sum ${{ env.IMAGE }} > ${{ env.IMAGE }}.sha256
          sha256sum ${{ env.IMAGE }}.xz > ${{ env.IMAGE }}.xz.sha256

      - name: "📋 Upload Compressed Image"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE }}.xz
          path: build/${{ env.IMAGE }}.xz

      - name: "📋 Upload Compressed Image Checksum"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE }}.xz.sha256
          path: build/${{ env.IMAGE }}.xz.sha256

      - name: "📋 Upload Image Checksum"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE }}.sha256
          path: build/${{ env.IMAGE }}.sha256

  create-release:
    needs: [ prepare, build ]
    if: needs.prepare.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Generate changelog"
        id: changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: ./cliff-release.toml
          args: --tag ${{ needs.prepare.outputs.release_tag }}

      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.release_tag }}
          name: MainsailOS ${{ needs.prepare.outputs.release_tag }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Download all artifacts"
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: "Upload Release Assets"
        run: |
          for asset_dir in artifacts/*; do
            for asset in "$asset_dir"/*; do
              echo "Uploading: $asset"
              gh release upload v${{ needs.prepare.outputs.release_tag }} "$asset" --clobber
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-changelog:
    needs: [ prepare, create-release ]
    if: needs.prepare.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4
        with:
          ref: "develop"
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: "Generate a changelog"
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - name: "Commit updated changelog"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(changelog): update changelog"
          file_pattern: CHANGELOG.md
